### ISSUE TITLE
Error calling NtOpenProcess. NTSTATUS: 0xC000000D, Error calling NtQueryInformationProcess. NTSTATUS: 0xC0000008, Error calling NtReadVirtualMemory. NTSTATUS: 0xC0000008

### ISSUE THREAD

**Issue by JPRobichaud1984** [ricardojoserf/NativeDump#1]
## Expected vs Actual Behavior
NativeDump successfully calls NtOpenProcess and completes operations.

## Specifications

 - Operating system: Windows 10 Pro 10.0.19045 N/A Build 19045
![image](https://github.com/ricardojoserf/NativeDump/assets/167451850/6b143f53-038b-4584-905a-5df775f9eb4b)

## Steps to Reproduce the Problem
I'm trying to run NativeDump and experiencing this same issue across multiple test VMs. I'm running Powershell as SYSTEM via Psexec. I've enabled all privs. 
![image](https://github.com/ricardojoserf/NativeDump/assets/167451850/42232971-527c-4b1b-8c74-5d48b758a096)

I've disabled PPL via registry (RunAsPPL is set to 0) as well as removed the EFI variable using Microsoft's Local Security Authority (LSA) Protected Process Opt-out process. I've also run PPLKiller successfully yet the issue persists. When looking into the error I believe it's a permissions issue but I'm not sure where else to look. Could you please point me in the right direction? Thanks.

**Comment by ricardojoserf** [comment]
Hi, is the compiled binary 64 bits? I think from the output you compiled It as 32 bits. Also after changing the ppl value in registra, did you reboot the machine?

**Comment by JPRobichaud1984** [comment]
Hello, I originally compiled as 'Release / Any CPU' but went back and specified 'Release / x64' and this appears to have solved the problem. 
![image](https://github.com/ricardojoserf/NativeDump/assets/167451850/d9deb8e5-1312-431d-bb72-538bef1d97d9)

To answer your other question though, yes I did reboot after the reg entry and the other removals of LSA protection. Thank you very much for helping with my obvious user error, I appreciate it!
