### ISSUE TITLE
Bypass PPL

### ISSUE THREAD

**Issue by lephong99** [ricardojoserf/NativeDump#7]
I have a question, can this tool bypass ppl when dumping lsass?

**Comment by ricardojoserf** [comment]
Hi @lephong99 . No, it would be impossible to use this technique is PPL is enabled, but you can always disable it changing the key "RunAsPPL" in "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa" to 0 and restarting the computer ;)
