### ISSUE TITLE
error parsing dmp file

### ISSUE THREAD

**Issue by mgff1835** [ricardojoserf/NativeDump#8]
trying to parse the generated dmp file from go,python flavours doesn't work
mimikatz

![mim](https://github.com/user-attachments/assets/64ede9b9-fc75-4140-a25c-b9c520af3d12)

pypykatz
![pypykatz](https://github.com/user-attachments/assets/75fad2f4-a3d7-4cb0-9a56-46b5415f1101)

windbg
![windbg](https://github.com/user-attachments/assets/663b2698-5248-4b77-9150-8140e6cc1ba0)

**Comment by ricardojoserf** [comment]
Hi @mgff1835 , the Minidump files generated can not be opened using WinDbg (it has never been possible). Regarding Pypykatz and Mimikatz, it depends on the Windows version and the Mimikatz version. 
If it is a Windows 11 or Windows Server 2022, you need one of the latest Mimikatz versions. In fact I needed to compile a specific branch to read the Minidumps from my Windows 11 system.
If you want you can send me an email to ricardojoserf@protonmail.com, I can send you the compiled Mimikatz I use or you can send me the Minidump file so I can analyze it.
